### ISSUE TITLE
[rush] In 5.57.0-dev.2, "rush change -v" fails if "rush install" has not been run

### ISSUE THREAD

**Issue by octogonz** [microsoft/rushstack#3054]
## Summary

While testing **5.57.0-dev.2** in our monorepo, we encountered CI failures like this:

```
Invoking "rush change --no-fetch --verify"
------------------------------------------

Rush Multi-Project Build Tool 5.57.0-dev.2 - https://rushjs.io
Node.js version is 14.18.2 (LTS)

Starting "rush change"

The target branch is origin/main

ERROR: Cannot find module '@hbo/hbo-web-rig/package.json' from
'/home/vsts/work/1/s/sandbox/hbomax-localization-sandbox'
```

👉I suspect that this is a regression introduced by PR #2968.

 

## Details

The regression occurred because as of **5.57.0-dev.2**, `rush change` is now calling into a code path that resolves rigs.  However `rush change -v` happens BEFORE `rush install`, so module resolution is not going to find the rig packages that it's looking for.

The error occurs during `Helpers.nodeResolveAsync(()` in this code:
https://github.com/microsoft/rushstack/blob/379f669138b80ef00f56a8bfb5509254b837ec9c/libraries/rig-package/src/RigConfig.ts#L361-L372

The failing `rush change` callstack looks like this:

```
  getResolvedProfileFolderAsync
  (.\common\temp\install-run\@microsoft+rush@5.57.0-dev.2\node_modules\@rushstack\rig-package\lib\RigConfig.js:199:48), <anonymous>:1:1)
at RigConfig.getResolvedProfileFolderAsync
  (.\common\temp\install-run\@microsoft+rush@5.57.0-dev.2\node_modules\@rushstack\rig-package\lib\RigConfig.js:199:48)
at ConfigurationFile._tryLoadConfigurationFileInRigAsync
  (.\common\temp\install-run\@microsoft+rush@5.57.0-dev.2\node_modules\@rushstack\heft-config-file\lib\ConfigurationFile.js:333:54)
at ConfigurationFile._loadConfigurationFileInnerAsync
  (.\common\temp\install-run\@microsoft+rush@5.57.0-dev.2\node_modules\@rushstack\heft-config-file\lib\ConfigurationFile.js:169:50)
at async ConfigurationFile._loadConfigurationFileInnerWithCacheAsync
  (.\common\temp\install-run\@microsoft+rush@5.57.0-dev.2\node_modules\@rushstack\heft-config-file\lib\ConfigurationFile.js:154:16)
at async ConfigurationFile.loadConfigurationFileForProjectAsync
  (.\common\temp\install-run\@microsoft+rush@5.57.0-dev.2\node_modules\@rushstack\heft-config-file\lib\ConfigurationFile.js:95:16)
at async ConfigurationFile.tryLoadConfigurationFileForProjectAsync
  (.\common\temp\install-run\@microsoft+rush@5.57.0-dev.2\node_modules\@rushstack\heft-config-file\lib\ConfigurationFile.js:103:20)
at async Function.tryLoadForProjectAsync
  (.\common\temp\install-run\@microsoft+rush@5.57.0-dev.2\node_modules\@microsoft\rush-lib\lib\api\RushProjectConfiguration.js:69:33)
at async ProjectChangeAnalyzer._getIgnoreMatcherForProjectAsync
  (.\common\temp\install-run\@microsoft+rush@5.57.0-dev.2\node_modules\@microsoft\rush-lib\lib\logic\ProjectChangeAnalyzer.js:242:38)
at async ProjectChangeAnalyzer._filterProjectDataAsync
  (.\common\temp\install-run\@microsoft+rush@5.57.0-dev.2\node_modules\@microsoft\rush-lib\lib\logic\ProjectChangeAnalyzer.js:116:31)
```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `rushVersion` from rush.json? | 5.57.0-dev.2 |
| `useWorkspaces` from rush.json? | true |

CC @dmichon-msft @iclanton @chengcyber @MickeyPhoenix @dharrie-hbo

**Comment by octogonz** [comment]
Fixed by PR #3056
