### PR TITLE
[heft] Fix some regressions involving jest.config.json resolution

### LINKED ISSUE #2745: [heft] Jest settings such as "testEnvironment" don't work with Heft >=0.32.0
I upgrade heft and the heft-node-rig and now I get this cryptic error message 

```
Error: Cannot find module "node" from "D:\dgts\dgiapi\server\config".
```

Here is my `config/jest.config.json`: 

```
{
  "extends": "@rushstack/heft-node-rig/profiles/default/config/jest.config.json",
  "collectCoverage": true,
  "testEnvironment": "node",
  "moduleDirectories": ["node_modules"],
  "moduleNameMapper": {
    "^jose/(.*)$": "<rootDir>/node_modules/jose/dist/node/cjs/$1"
  }
}
```

### PR DESCRIPTION
**Pull request by octogonz**
## Summary

Fixes #2745

## Details

Heft 0.32.0 completely changes how **jest.config.json** gets resolved.  

- This PR fixes a problem where "testEnvironment" was incorrectly resolved as a module path
- To prevent rigged projects from needing a dependency on `"@rushstack/heft-jest-plugin`, it adds a special case for resolving paths like `"@rushstack/heft-jest-plugin/lib/exports/jest-global-setup.js"`

## How it was tested

With these changes, plus PR #2760, I was finally able to  migrate our large monorepo to use the latest Heft.

CC @D4N14L @iclanton

### CODE REVIEW

**Review by iclanton — APPROVED** [review]

**Review by D4N14L — CHANGES_REQUESTED** [review]
I disagree with this change. This is a module path. It is a quirk of Jest in how it resolves the module. Internally in Jest it will resolve to `jest-environment-*` where `*` is the value specified in the field. `jest-environment-node` is normally resolved within the Jest package itself, since it is a dependency there, same for `jest-environment-jsdom`. However, some aren't available by default. For example, we use `jest-environment-jsdom-sixteen` which isn't included in Jest and needs to be a dependency of the package being tested (or currently, the Heft rig). For this reason, specifying the full package name is completely valid and should be resolved.

A possibly better solution would be to allow certain keywords or patterns to be ignored by `heft-config-file` so that it gets passed through to Jest without being resolved. This will maintain existing functionality while allowing us rig resolution for non-matching values.

The `<rootDir>` bit however looks good!

**Comment by octogonz** [comment]
> I disagree with this change. This is a module path. It is a quirk of Jest in how it resolves the module. Internally in Jest it will resolve to `jest-environment-*` where `*` is the value specified in the field. `jest-environment-node` is normally resolved within the Jest package itself, since it is a dependency there, same for `jest-environment-jsdom`. However, some aren't available by default. For example, we use `jest-environment-jsdom-sixteen` which isn't included in Jest and needs to be a dependency of the package being tested (or currently, the Heft rig). For this reason, specifying the full package name is completely valid and should be resolved.
> 
> A possibly better solution would be to allow certain keywords or patterns to be ignored by `heft-config-file` so that it gets passed through to Jest without being resolved. This will maintain existing functionality while allowing us rig resolution for non-matching values.

@D4N14L The actual resolution looks like this:

[jest-resolve/src/utils.ts](https://github.com/facebook/jest/blob/d6fb0d8fb0d43a17f90c7a5a6590257df2f2f6f5/packages/jest-resolve/src/utils.ts#L96)
```ts
/**
 * Finds the test environment to use:
 *
 * 1. looks for jest-environment-<name> relative to project.
 * 1. looks for jest-environment-<name> relative to Jest.
 * 1. looks for <name> relative to project.
 * 1. looks for <name> relative to Jest.
 */
export const resolveTestEnvironment = ({
  rootDir,
  testEnvironment: filePath,
  // TODO: remove default in Jest 28
  requireResolveFunction = require.resolve,
}: {
  rootDir: Config.Path;
  testEnvironment: string;
  requireResolveFunction?: (moduleName: string) => string;
}): string =>
  resolveWithPrefix(undefined, {
    filePath,
    humanOptionName: 'Test environment',
    optionName: 'testEnvironment',
    prefix: 'jest-environment-',
    requireResolveFunction,
    rootDir,
  });
```

...and then the `resolveWithPrefix()` looks like this:
```ts
  const fileName = replaceRootDirInPath(rootDir, filePath);
  let module = Resolver.findNodeModule(`${prefix}${fileName}`, {
    basedir: rootDir,
    resolver: resolver || undefined,
  });
  if (module) {
    return module;
  }

  try {
    return requireResolveFunction(`${prefix}${fileName}`);
  } catch {}

  module = Resolver.findNodeModule(fileName, {
    basedir: rootDir,
    resolver: resolver || undefined,
  });
  if (module) {
    return module;
  }

  try {
    return requireResolveFunction(fileName);
  } catch {}

  throw createValidationError(
```

This same pattern is used for other options like `watchPlugin`, `runner`, `sequencer`.

Maybe Heft should get all involved with trying to reimplement these Jest internals with rig support. Or maybe Heft could import the implementations from the `jest-resolve` package.

However the immediate problem is that `testEnvironment` is unusable right now for the 99% most common values of `node` and `jsdom`.  So we should start with a quick fix for that problem, then circle back with a more full-featured solution. This is the same mentality of PR #2755 and PR #2760.

**Review by D4N14L — APPROVED** [review]
Approving to allow for getting a fix out for basic values. @octogonz could you file an issue for package resolution of those fields?

**Comment by octogonz** [comment]
Thanks!  We can add the other fields to #2745 since they will all get solved together.

This PR does not close that issue, since it's just a temporary workaround.

**Comment by octogonz** [comment]
Released with Heft 0.33.1
