### PR TITLE
[heft-jest-plugin] Improve module resolution for Jest configuration files

### LINKED ISSUE #2745: [heft] Jest settings such as "testEnvironment" don't work with Heft >=0.32.0
I upgrade heft and the heft-node-rig and now I get this cryptic error message 

```
Error: Cannot find module "node" from "D:\dgts\dgiapi\server\config".
```

Here is my `config/jest.config.json`: 

```
{
  "extends": "@rushstack/heft-node-rig/profiles/default/config/jest.config.json",
  "collectCoverage": true,
  "testEnvironment": "node",
  "moduleDirectories": ["node_modules"],
  "moduleNameMapper": {
    "^jose/(.*)$": "<rootDir>/node_modules/jose/dist/node/cjs/$1"
  }
}
```

### PR DESCRIPTION
**Pull request by D4N14L**
## Summary

Fixes #2745

- Improve module resolution for Jest configuration files loaded using `heft-jest-plugin` such that it more closely resembles how default Jest functions
- Add tokens to allow for referencing special directories in non-path (but still 'pathy') fields like `moduleNameMapper`

## Details

In using JSON configuration files that were resolved fully before passing to Jest, we introduced a few limitations. Namely:
- All modules being referenced _must_ be available in the package the configuration file is sourced from
- No auto-prefixing for certain Jest fields
- No runtime resolution of paths in non-module fields

Unfortunately, this meant that we had introduced a few regressions in comparison with default Jest that we do not want to get rid of. Specifically, a few features that are being added back are:
- Allowing certain fields to resolve to a prefixed package name (ex. `jest-environment-` prefix for `testEnvironment` option)
- Allowing certain fields to silently fail module resolution and pass the value through to Jest when a module isn't directly resolvable from the package containing the configuration file (ex. `jest-environment-node` or `node` are resolved from Jest for `testEnvironment` option)

Additionally, by restricting ourselves to JSON files (instead of JSON and .js, as is true with default Jest), we removed the ability to run JavaScript code to resolve paths relative to the configuration file in non-path (but still pathy) fields. For example, the ability to create `moduleNameMappers` that map to modules within the project containing the configuration file was lost. To work around this, two new tokens were added which will be mapped/replaced during resolution:
- `<configDir>` to reference paths relative to the directory that the config file is in. This will always refer to the configuration file that contains the `<configDir>` tag, unlike `<rootDir>` which will always reference the build folder
- `<packageDir:...>` token to reference a path relative to the root of a dependency package, where `...` is the package name. This package is resolved using Node module resolution relative to the directory that the config file is in

## How it was tested
- Added more unit tests to cover these cases
- Rebuilt projects that are using the `heft-jest-plugin` and confirmed that their tests did not fail

### CODE REVIEW

File: libraries/heft-config-file/src/ConfigurationFile.ts [hunk 1]
```diff
@@ -55,7 +55,12 @@ export enum PathResolutionMethod {
    * Treat the property as a NodeJS-style require/import reference and resolve using standard
    * NodeJS filesystem resolution
    */
-  NodeResolve
+  NodeResolve,
```
Comment (iclanton) [inline libraries/heft-config-file/src/ConfigurationFile.ts:58]: Wonder why I capitalized this.

File: libraries/heft-config-file/src/ConfigurationFile.ts [hunk 2]
```diff
@@ -645,8 +648,20 @@ export class ConfigurationFile<TConfigurationFile> {
         });
       }
 
+      case PathResolutionMethod.custom: {
+        if (!metadata.customResolver) {
+          throw new Error(
+            `PathResolutionMethod "${PathResolutionMethod[resolutionMethod]}" was provided, but no custom ` +
+              'resolver was found.'
```
Comment (iclanton) [inline libraries/heft-config-file/src/ConfigurationFile.ts:655]:
```suggestion
            `The pathResolutionMethod was set to "${PathResolutionMethod[resolutionMethod]}" was, but a custom ` +
              'resolver was not provided.'
```

File: libraries/heft-config-file/src/ConfigurationFile.ts (hunk 1 above)
Comment (octogonz) [reply libraries/heft-config-file/src/ConfigurationFile.ts:58]: Enum members are conventionally capitalized.  I almost implemented an ESLint rule to enforce that, but IIRC it would break a lot of legacy code.

Comment (octogonz) [reply libraries/heft-config-file/src/ConfigurationFile.ts:58]: Maybe we should make a lint rule.

Comment (iclanton) [reply libraries/heft-config-file/src/ConfigurationFile.ts:58]: It's probably fine to rename it and make a note in the changelog.

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 3]
```diff
@@ -47,11 +54,17 @@ export interface IHeftJestConfiguration extends Config.InitialOptions {}
  * @internal
  */
 export class JestPlugin implements IHeftPlugin<IJestPluginOptions> {
+  private static _ownPackageFolder: string = path.resolve(__dirname, '..');
```
Comment (iclanton) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts:57]: Do you have a test that ensures that this remains valid, in case files get moved around?

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 4]
```diff
@@ -283,33 +269,67 @@ export class JestPlugin implements IHeftPlugin<IJestPluginOptions> {
...
+          modulePrefix: 'jest-watch-',
+          ignoreMissingModule: true
+        }),
+        '$.watchPlugins.*[?(@property == 0)]': JestPlugin._getJsonPathMetadata({
+          // First entry in [ path, options ]
+          buildFolder,
+          resolveAsModule: true,
+          modulePrefix: 'jest-watch-',
+          ignoreMissingModule: true
+        })
```
Comment (iclanton) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts:332]: These two resolvers look identical.

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 5]
```diff
@@ -47,11 +54,17 @@ export interface IHeftJestConfiguration extends Config.InitialOptions {}
  * @internal
  */
 export class JestPlugin implements IHeftPlugin<IJestPluginOptions> {
+  private static _ownPackageFolder: string = path.resolve(__dirname, '..');
+  private static _rootDirToken: string = '<rootDir>';
+  private static _configDirToken: string = '<configDir>';
+  private static _packageCaptureGroup: string = 'package';
+  private static _packageDirRegex: RegExp = new RegExp(
+    `^<packageDir:\\s*(?<${JestPlugin._packageCaptureGroup}>[^\\s^]*)\\s*>`
+  );
```
Comment (iclanton) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts:63]: Might be cleaner to put these up with the other consts outside the class.

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 6]
```diff
@@ -379,6 +399,101 @@ export class JestPlugin implements IHeftPlugin<IJestPluginOptions> {
     ];
   }
 
+  // Resolve all specified properties using Node resolution, and replace <rootDir> with the same rootDir
+  // that we provide to Jest. Resolve if we modified since paths containing <rootDir> should be absolute.
+  private static _getJsonPathMetadata(options: IJsonPathMetadataOptions): IJsonPathMetadata {
```
Comment (iclanton) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts:404]: Seems like this does more than the first sentence implies.

```suggestion
  /**
   * Resolve all specified properties using Node resolution, and replace <rootDir> with the same rootDir
   * that we provide to Jest. Resolve if we modified since paths containing <rootDir> should be absolute.
   */
  private static _getJsonPathMetadata(options: IJsonPathMetadataOptions): IJsonPathMetadata {
```

What do you mean by this?:

>Resolve if we modified since paths containing <rootDir> should be absolute.

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 7]
```diff
@@ -379,6 +399,101 @@ export class JestPlugin implements IHeftPlugin<IJestPluginOptions> {
...
+    return {
+      customResolver: (configurationFilePath: string, value: string) => {
+        const configurationFileDir: string = path.dirname(configurationFilePath);
+        let packageDirMatches: RegExpExecArray | null;
+
+        // Compare with replaceRootDirInPath() from here:
+        // https://github.com/facebook/jest/blob/5f4dd187d89070d07617444186684c20d9213031/packages/jest-config/src/utils.ts#L58
+        if (value.startsWith(JestPlugin._rootDirToken)) {
+          // Example:  <rootDir>/path/to/file.js
+          const restOfPath: string = path.normalize('./' + value.substr(JestPlugin._rootDirToken.length));
```
Comment (iclanton) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts:419]: The `normalize` calls may be unnecessary.

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 8]
```diff
@@ -379,6 +399,101 @@ export class JestPlugin implements IHeftPlugin<IJestPluginOptions> {
...
+                `"${configurationFilePath}".`
+            );
+          }
+          // Resolve to the root of the package (not the module referenced by the package)
+          const resolvedPackagePath: string = Import.resolvePackage({
+            baseFolderPath: path.dirname(configurationFilePath),
+            packageName
+          });
+          // longestMatch should match the entire tag
+          const longestMatch: number = Math.max(...packageDirMatches.map((match) => match.length));
```
Comment (iclanton) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts:444]: Shouldn't this just be the first entry in the matches array?

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 9]
```diff
@@ -379,6 +399,101 @@ export class JestPlugin implements IHeftPlugin<IJestPluginOptions> {
...
+          if (!packageName) {
+            throw new Error(
+              `Could not parse required field "${JestPlugin._packageCaptureGroup}" from "packageDir" tag in ` +
+                `"${configurationFilePath}".`
+            );
+          }
+          // Resolve to the root of the package (not the module referenced by the package)
+          const resolvedPackagePath: string = Import.resolvePackage({
+            baseFolderPath: path.dirname(configurationFilePath),
+            packageName
```
Comment (iclanton) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts]: What if they specify a module path inside a package? You could filter that out via the regexp by only allowing things that look like package names.

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 10]
```diff
@@ -379,6 +399,101 @@ export class JestPlugin implements IHeftPlugin<IJestPluginOptions> {
...
+
+        // Return early, since the remainder of this function is used to resolve module paths
+        if (!options.resolveAsModule) {
+          return value;
+        }
+
+        // The normal PathResolutionMethod.NodeResolve will generally not be able to find @rushstack/heft-jest-plugin
+        // from a project that is using a rig.  Since it is important, and it is our own package, we resolve it
+        // manually as a special case.
+        const PLUGIN_PACKAGE_NAME: string = '@rushstack/heft-jest-plugin';
```
Comment (iclanton) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts]: Move this up with the other consts?

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts (hunk 7 above)
Comment (D4N14L) [reply heft-plugins/heft-jest-plugin/src/JestPlugin.ts:419]: I'm going to leave it this way, only because that's what happens inside of Jest and I don't want to tweak that. This came in after @octogonz had an issue with how rootDir was substituted in, so I'd err on the side of "safe"

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts (hunk 8 above)
Comment (D4N14L) [reply heft-plugins/heft-jest-plugin/src/JestPlugin.ts:444]: Ah, interesting! Will use that.

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts (hunk 9 above)
Comment (D4N14L) [reply heft-plugins/heft-jest-plugin/src/JestPlugin.ts]: Going to catch it after running regexp so that a friendly error can be outputted.

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts (hunk 3 above)
Comment (D4N14L) [reply heft-plugins/heft-jest-plugin/src/JestPlugin.ts]: Curious, never made one for this purpose... do we have a standard way of doing this?

File: common/config/rush/pnpm-lock.yaml [hunk 11]
```diff
@@ -6948,6 +6952,34 @@ packages:
       - utf-8-validate
     dev: true
 
+  /jest-config/25.4.0:
```
Comment (iclanton) [inline common/config/rush/pnpm-lock.yaml:6955]: Shouldn't this already have been installed?

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts (hunk 3 above)
Comment (iclanton) [reply heft-plugins/heft-jest-plugin/src/JestPlugin.ts]: I don't think so. Might be easiest to put this in a `constants.ts` file and have a test that uses `PackageJsonLookup` to verify that the path it finds is correct.

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 12]
```diff
@@ -414,85 +414,76 @@ export class JestPlugin implements IHeftPlugin<IJestPluginOptions> {
...
-            throw e;
-          }
+        if (propertyValue.startsWith(PLUGIN_PACKAGE_NAME)) {
+          const restOfPath: string = path.normalize('./' + propertyValue.substr(PLUGIN_PACKAGE_NAME.length));
+          return path.join(OWN_PACKAGE_FOLDER, restOfPath);
         }
 
-        return value;
+        return !options.modulePrefix
+          ? jestResolve(/*resolver:*/ undefined, {
```
Comment (iclanton) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts:475]: What is this first argument for normally?

**Comment by D4N14L** [comment]
@octogonz Ian messaged separately saying looks good but wanted you to take a look/try it out on your repo given that it's a big change to how the resolution of the modules is done. Could you take a look?

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts (hunk 12 above)
Comment (D4N14L) [reply heft-plugins/heft-jest-plugin/src/JestPlugin.ts:475]: Normally it's for the resolver loaded through the `resolver` setting on the Jest configuration. We _could_ add support for it, however it would require some tweaks to the `heft-config-file` package to provide us the current state of the configuration file/the unresolved current configuration file + the resolved state of the combined configuration file up to this point.

File: common/config/rush/pnpm-lock.yaml (hunk 11 above)
Comment (D4N14L) [reply common/config/rush/pnpm-lock.yaml:6955]: Normally yes, but it seems that the version descriptor is a bit looser for Jest and it chooses to install the 25.5.0 version. Unsure why that is. But I figured I would try to keep the versioning consistent with the one it was released with.

File: libraries/heft-config-file/src/ConfigurationFile.ts (hunk 1 above)
Comment (octogonz) [reply libraries/heft-config-file/src/ConfigurationFile.ts:58]: Let's handle it in a separate PR.

My vote would be do one big PR that renames all the Heft API enums to use `InitialCaps`.

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 13]
```diff
@@ -379,6 +393,102 @@ export class JestPlugin implements IHeftPlugin<IJestPluginOptions> {
...
+        // https://github.com/facebook/jest/blob/5f4dd187d89070d07617444186684c20d9213031/packages/jest-config/src/utils.ts#L58
+        if (propertyValue.startsWith(ROOTDIR_TOKEN)) {
+          // Example:  <rootDir>/path/to/file.js
+          const restOfPath: string = path.normalize('./' + propertyValue.substr(ROOTDIR_TOKEN.length));
+          propertyValue = path.resolve(options.buildFolder, restOfPath);
+        } else if (propertyValue.startsWith(CONFIGDIR_TOKEN)) {
+          // Example:  <configDir>/path/to/file.js
+          const restOfPath: string = path.normalize('./' + propertyValue.substr(CONFIGDIR_TOKEN.length));
+          propertyValue = path.resolve(configurationFileDir, restOfPath);
+        } else if ((packageDirMatches = PACKAGEDIR_REGEX.exec(propertyValue)) !== null) {
```
Comment (octogonz) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts:424]: Our ESLint rules should forbid assignments inside a conditional

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 14]
```diff
@@ -43,15 +48,23 @@ export interface IJestPluginOptions {
...
 
+const PLUGIN_NAME: string = 'JestPlugin';
+const PLUGIN_SCHEMA_PATH: string = `${__dirname}/schemas/heft-jest-plugin.schema.json`;
+const JEST_CONFIGURATION_LOCATION: string = `config/jest.config.json`;
+const OWN_PACKAGE_FOLDER: string = path.resolve(__dirname, '..');
+
+const ROOTDIR_TOKEN: string = '<rootDir>';
+const CONFIGDIR_TOKEN: string = '<configDir>';
+const PACKAGE_CAPTUREGROUP: string = 'package';
+const PACKAGEDIR_REGEX: RegExp = new RegExp(`^<packageDir:\\s*(?<${PACKAGE_CAPTUREGROUP}>[^\\s^]*)\\s*>`);
```
Comment (octogonz) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts:59]:
```suggestion
const PACKAGEDIR_REGEX: RegExp = /^<packageDir:\s*(?<package>[^\s^]*)\s*>/;
```
RegExp's are difficult enough to read already without `` ` `` `` ` `` escaping superimposed on them. 😁

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 15]
```diff
@@ -43,15 +48,23 @@ export interface IJestPluginOptions {
...
+
 /**
```
Comment (octogonz) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts:61]: Why is your NPM package name pattern "Any characters that are not spaces or carets"?  (`[^\s^]`)  

Did you mean to say any characters that are not spaces or `>` delimiters?

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 16]
```diff
@@ -379,6 +393,102 @@ export class JestPlugin implements IHeftPlugin<IJestPluginOptions> {
...
+          if (!packageName) {
+            throw new Error(
+              `Could not parse package name from "packageDir" token ` +
+                (propertyName ? `of property "${propertyName}" ` : '') +
+                `in "${configurationFilePath}".`
+            );
+          }
+
+          // Prevent module paths from being specified by limiting the number of '/' characters present
+          if (packageName.match(/^((@[^\/]+\/)|[^@])[^\/]+\/.*$/)) {
```
Comment (octogonz) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts:436]: Use the `PackageName` API from node-core-library

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 17]
```diff
@@ -43,15 +48,23 @@ export interface IJestPluginOptions {
 
 export interface IHeftJestConfiguration extends Config.InitialOptions {}
 
+const PLUGIN_NAME: string = 'JestPlugin';
+const PLUGIN_SCHEMA_PATH: string = `${__dirname}/schemas/heft-jest-plugin.schema.json`;
```
Comment (octogonz) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts:52]: Use `path.json()`.  On Windows `__dirname` has backslashes which would produce `C:\path\to/schemas/heft-jest-plugin.schema.json`

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 18]
```diff
@@ -379,6 +393,102 @@ export class JestPlugin implements IHeftPlugin<IJestPluginOptions> {
...
+        }
+
+        // Return early, since the remainder of this function is used to resolve module paths
+        if (!options.resolveAsModule) {
+          return propertyValue;
+        }
+
+        // Example:  @rushstack/heft-jest-plugin
+        if (propertyValue === PLUGIN_PACKAGE_NAME) {
+          return OWN_PACKAGE_FOLDER;
```
Comment (octogonz) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts:465]: `PLUGIN_PACKAGE_NAME` and `OWN_PACKAGE_FOLDER` should probably be declared together, and should have consistent names like `OWN_PACKAGE_NAME`

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 19]
```diff
@@ -26,15 +27,19 @@ import {
...
-const PLUGIN_NAME: string = 'JestPlugin';
-const PLUGIN_SCHEMA_PATH: string = `${__dirname}/schemas/heft-jest-plugin.schema.json`;
-const JEST_CONFIGURATION_LOCATION: string = `config/jest.config.json`;
+
+interface IJsonPathMetadataOptions {
+  buildFolder: string;
+  resolveAsModule?: boolean;
+  modulePrefix?: string;
+  ignoreMissingModule?: boolean;
+}
```
Comment (octogonz) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts:42]: This interface needs good documentation for each member.  It is the Rosetta stone for understanding all the components of your `jsonPathMetadata`

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 20]
```diff
@@ -283,33 +275,55 @@ export class JestPlugin implements IHeftPlugin<IJestPluginOptions> {
...
+          modulePrefix: 'jest-runner-',
+          ignoreMissingModule: true
+        }),
+        '$.snapshotResolver': jestResolveMetadata,
         // This is a name like "jsdom" that gets mapped into a package name like "jest-environment-jsdom"
-        // '$.testEnvironment': string
-        '$.testResultsProcessor': nodeResolveMetadata,
-        '$.testRunner': nodeResolveMetadata,
-        '$.testSequencer': nodeResolveMetadata,
+        '$.testEnvironment': JestPlugin._getJsonPathMetadata({
```
Comment (octogonz) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts:295]: For these it would be useful to mention [resolveWithPrefix()](https://github.com/facebook/jest/blob/d6fb0d8fb0d43a17f90c7a5a6590257df2f2f6f5/packages/jest-resolve/src/utils.ts#L36) and then cite each Jest rule like [resolveTestEnvironment](https://github.com/facebook/jest/blob/d6fb0d8fb0d43a17f90c7a5a6590257df2f2f6f5/packages/jest-resolve/src/utils.ts#L110).  

This would be very valuable if a future version of Jest changes the logic, and someone needs to figure out what changed since Heft's implementation was put together.

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts (hunk 15 above)
Comment (D4N14L) [reply heft-plugins/heft-jest-plugin/src/JestPlugin.ts:61]: Good catch!

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 21]
```diff
@@ -379,6 +393,102 @@ export class JestPlugin implements IHeftPlugin<IJestPluginOptions> {
...
+          return OWN_PACKAGE_FOLDER;
+        }
+
+        // Example:  @rushstack/heft-jest-plugin/path/to/file.js
+        if (propertyValue.startsWith(PLUGIN_PACKAGE_NAME)) {
+          const restOfPath: string = path.normalize('./' + propertyValue.substr(PLUGIN_PACKAGE_NAME.length));
+          return path.join(OWN_PACKAGE_FOLDER, restOfPath);
+        }
+
+        return !options.modulePrefix
```
Comment (octogonz) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts:474]: `!` `?` `:` is hurting my head here.  The `?` operator is meant to avoid an `if` statement for very simple logic. This ain't simple. :-)

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts [hunk 22]
```diff
@@ -379,6 +393,102 @@ export class JestPlugin implements IHeftPlugin<IJestPluginOptions> {
...
+          ? jestResolve(/*resolver:*/ undefined, {
+              rootDir: configurationFileDir,
+              filePath: propertyValue,
+              key: propertyName
+            })
+          : jestResolveWithPrefix(/*resolver:*/ undefined, {
+              rootDir: configurationFileDir,
+              filePath: propertyValue,
+              prefix: options.modulePrefix,
+              humanOptionName: propertyName,
```
Comment (octogonz) [inline heft-plugins/heft-jest-plugin/src/JestPlugin.ts:484]: Jest's implementation specifies the `humanOptionName` as an English phrase -- do we care about that?
```js
  resolveWithPrefix(undefined, {
    filePath,
    humanOptionName: 'Test environment',
    optionName: 'testEnvironment',
    prefix: 'jest-environment-',
    requireResolveFunction,
    rootDir,
  });
```

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts (hunk 12 above)
Comment (octogonz) [reply heft-plugins/heft-jest-plugin/src/JestPlugin.ts:475]: Circling back to https://github.com/microsoft/rushstack/pull/2761 :

Suppose that I specify `"testEnvirionment": "shpadoinkle"` which Jest would normally resolve as `jest-environment-shpadoinkle`.

How does `jest-environment-shpadoinkle` get resolved now?  Can it be provided by the rig?  Can it be overridden by my local project's **package.json**?

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts (hunk 22 above)
Comment (D4N14L) [reply heft-plugins/heft-jest-plugin/src/JestPlugin.ts:484]: I'm not too concerned, no. Both of these fields are used for logging purposes, and setting them to the same value doesn't change the understanding of the logging message; if anything, it's more specific:
```
throw createValidationError(
    `  ${humanOptionName} ${chalk.bold(
      fileName,
    )} cannot be found. Make sure the ${chalk.bold(
      optionName,
    )} configuration option points to an existing node module.`,
  );
```

File: heft-plugins/heft-jest-plugin/src/JestPlugin.ts (hunk 12 above)
Comment (D4N14L) [reply heft-plugins/heft-jest-plugin/src/JestPlugin.ts]: It can be provided by rig packages. Currently it would be resolved in this manner for `testEnvironment` (or other prefixed values like `jest-runner-`):
- resolve the prefixed package name (ex. `jsdom` -> `jest-environment-jsdom`) relative to the directory the configuration file is specified in using Node resolution
- resolve the prefixed package name from `jest-config` using `require.resolve`
- resolve the unprefixed package name relative to the directory the configuration file is specified in using Node resolution
- resolve the unprefixed package name from `jest-config` using `require.resolve`

**Review by iclanton — APPROVED** [review]
