### ISSUE TITLE
[heft] Jest settings such as "testEnvironment" don't work with Heft >=0.32.0

### ISSUE THREAD

**Issue by jessekrubin** [microsoft/rushstack#2745]
I upgrade heft and the heft-node-rig and now I get this cryptic error message 

```
Error: Cannot find module "node" from "D:\dgts\dgiapi\server\config".
```

Here is my `config/jest.config.json`: 

```
{
  "extends": "@rushstack/heft-node-rig/profiles/default/config/jest.config.json",
  "collectCoverage": true,
  "testEnvironment": "node",
  "moduleDirectories": ["node_modules"],
  "moduleNameMapper": {
    "^jose/(.*)$": "<rootDir>/node_modules/jose/dist/node/cjs/$1"
  }
}
```

**Comment by jessekrubin** [comment]
Repo with bug recreation: https://github.com/jessekrubin/rushstack-heft-bug-2745

**Comment by jessekrubin** [comment]
This is maddening. I had to rollback any lib/package that doesn't have a super simple jest config to heft 0.31.5

**Comment by octogonz** [comment]
From [CHANGELOG.md](https://github.com/microsoft/rushstack/blob/master/apps/heft/CHANGELOG.md):

> ## 0.32.0
> Fri, 11 Jun 2021 00:34:02 GMT
> 
> ### Minor changes
> 
> - (BREAKING CHANGE) Remove Jest plugin from Heft. To consume the Jest plugin, add @rushstack/heft-jest-plugin as a dependency and include it in heft.json. See UPGRADING.md for more information.

The changes are explained in [UPGRADING.md](https://github.com/microsoft/rushstack/blob/master/apps/heft/UPGRADING.md)

**Comment by octogonz** [comment]
@jessekrubin Let us know if you still have questions, or if we should close this issue.

**Comment by octogonz** [comment]
This error is caused by the `"testEnvironment": "node"` setting.

I confirmed that the setting works correctly with Heft 0.30.6 but fails with Heft 0.32.0.  

👉This seems to be a regression caused by the `@rushstack/heft-jest-plugin` refactoring.

Here's a workaround (I confirmed that you need both steps; neither step is sufficient by itself):
- Add `"jest-environment-node": "~25.4.0"` as a dev dependency for your project
- specify `"testEnvironment": "jest-environment-node"` (instead of `"node"`) in **jest.config.json**
...but this workaround should not be necessary. Heft is supposed to provide the core Jest dependencies, so that projects don't need to deal with that.

CC @D4N14L @iclanton

**Comment by octogonz** [comment]
PR #2761 fixes the regression for the most common settings `"testEnvironment": "node"` and `"testEnvironment": "jsdom"`.

However it does not correctly implement rigging for module paths.  And also I noticed that several other (less common) settings are impacted by the same issue: `watchPlugin`, `runner`, `sequencer`

**Comment by octogonz** [comment]
From my investigation, the actual resolution looks like this:

[jest-resolve/src/utils.ts](https://github.com/facebook/jest/blob/d6fb0d8fb0d43a17f90c7a5a6590257df2f2f6f5/packages/jest-resolve/src/utils.ts#L96)
```ts
/**
 * Finds the test environment to use:
 *
 * 1. looks for jest-environment-<name> relative to project.
 * 1. looks for jest-environment-<name> relative to Jest.
 * 1. looks for <name> relative to project.
 * 1. looks for <name> relative to Jest.
 */
export const resolveTestEnvironment = ({
  rootDir,
  testEnvironment: filePath,
  // TODO: remove default in Jest 28
  requireResolveFunction = require.resolve,
}: {
  rootDir: Config.Path;
  testEnvironment: string;
  requireResolveFunction?: (moduleName: string) => string;
}): string =>
  resolveWithPrefix(undefined, {
    filePath,
    humanOptionName: 'Test environment',
    optionName: 'testEnvironment',
    prefix: 'jest-environment-',
    requireResolveFunction,
    rootDir,
  });
```

...and then the `resolveWithPrefix()` looks like this:
```ts
  const fileName = replaceRootDirInPath(rootDir, filePath);
  let module = Resolver.findNodeModule(`${prefix}${fileName}`, {
    basedir: rootDir,
    resolver: resolver || undefined,
  });
  if (module) {
    return module;
  }

  try {
    return requireResolveFunction(`${prefix}${fileName}`);
  } catch {}

  module = Resolver.findNodeModule(fileName, {
    basedir: rootDir,
    resolver: resolver || undefined,
  });
  if (module) {
    return module;
  }

  try {
    return requireResolveFunction(fileName);
  } catch {}

  throw createValidationError(
```

The complete solution will need to make that logic fully riggable.
