### PR TITLE
[heft-typescript-plugin] feat: support typescript 5.6

### LINKED ISSUE #4921: [heft] typescript plugin does not work with Typescript 5.6.2
## Summary

Just attempted to upgrade to Typescript v5.6.2
Unfortunately something has changed in the typescript internals and now the heft-typescript-plugin crashes when attempting to do a build with the error `builderProgram.getState is not a function` 

## Repro steps

1. Install latest Heft
2. Install latest heft-typescript-plugin
3. Configure a typescript build phase
4. Run `heft build`

  **Expected result:** Program compiles normally

  **Actual result:** Get a crash `builderPrograms.getState is not a function` (not sure how to get heft to give me a stacktrace)

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.66.18 / @rushstack/heft-typescript-plugin 0.5.0 |
| Operating system? | Linux |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | v20.15.1 |

### PR DESCRIPTION
**Pull request by UberMouse**
## Summary

Updates the heft typescript plugin for breaking changes made to the typescript internals that the plugin relies on

## Details

The breakage was caused by an internal change of `BuilderProgram.getState()` to `BuilderProgram.state` in [this](https://github.com/microsoft/TypeScript/commit/b9d96df61f01375da6504f37a31151cfdce0645c) commit. 

Changing the code to use `.state` instead of `.getState()` if `state` is defined was the only change required

Fixes #4921 

## How it was tested

Linked into our monorepo and a full build of all packages was done
Then everything was started in watch mode and a webpack based package was started up to verify that watch mode changes are still picked up correctly

Our monorepo does not use heft for linting so I haven't tested if this change still works correctly with the heft lint plugin

### CODE REVIEW

**Comment by UberMouse** [comment]
Hmm, seems obvious now but the CI doesn't work because the change only functions when tested against a typescript 5.6 based compiler but rushstack repo is on an older typescript version :shrug: 

Anyway, I'll leave this here as an example

File: heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts [hunk 1]
```diff
@@ -1301,8 +1301,8 @@ function getFilesToTranspileFromBuilderProgram(
   builderProgram: TTypescript.BuilderProgram
 ): Map<string, string> {
   const changedFilesSet: Set<string> = (
-    builderProgram as unknown as { getState(): { changedFilesSet: Set<string> } }
-  ).getState().changedFilesSet;
+    builderProgram as unknown as { state: { changedFilesSet: Set<string> } }
+  ).state.changedFilesSet;
```
Comment (jakebailey) [inline heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts:1305]: To not break TS <5.6, you could just declare both and then use `state` if it's present, otherwise call `getState`.

Comment (jakebailey) [reply heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts:1305]: As in:

```diff ts
diff --git a/heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts b/heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts
index f1f4db242a..88e940d2f3 100644
--- a/heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts
+++ b/heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts
@@ -1300,9 +1300,13 @@ export class TypeScriptBuilder {
 function getFilesToTranspileFromBuilderProgram(
   builderProgram: TTypescript.BuilderProgram
 ): Map<string, string> {
-  const changedFilesSet: Set<string> = (
-    builderProgram as unknown as { getState(): { changedFilesSet: Set<string> } }
-  ).getState().changedFilesSet;
+  const builderProgramWithState = builderProgram as unknown as {
+    state?: { changedFilesSet: Set<string> };
+    getState?(): { changedFilesSet: Set<string> };
+  };
+
+  const changedFilesSet: Set<string> =
+    builderProgramWithState.state?.changedFilesSet ?? builderProgramWithState.getState!().changedFilesSet;
   const filesToTranspile: Map<string, string> = new Map();
   for (const fileName of changedFilesSet) {
     const sourceFile: TTypescript.SourceFile | undefined = builderProgram.getSourceFile(fileName);
```

Comment (jakebailey) [reply heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts:1305]: Unfortunately the repo can't update to 5.6 because this fix isn't released and the repo needs itself working on npm to publish :(

Comment (UberMouse) [reply heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts:1305]: Too right mate. Changes incoming

File: common/changes/@rushstack/heft-typescript-plugin/heft-typescript-plugin-typescript-56-support_2024-10-13-22-44.json [hunk 2]
```diff
@@ -0,0 +1,10 @@
+{
+  "changes": [
+    {
+      "packageName": "@rushstack/heft-typescript-plugin",
+      "comment": "Support typescript v5.6",
+      "type": "minor"
```
Comment (jakebailey) [inline common/changes/@rushstack/heft-typescript-plugin/heft-typescript-plugin-typescript-56-support_2024-10-13-22-44.json:6]: I think `patch` is ok here

File: heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts [hunk 3]
```diff
@@ -1297,12 +1297,16 @@ export class TypeScriptBuilder {
   }
 }
 
+type BuilderProgramWithInternals = TTypescript.BuilderProgram & {
+  state?: { changedFilesSet: Set<string> };
+  getState(): { changedFilesSet: Set<string> };
+};
```
Comment (iclanton) [inline heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts:1303]: This should probaly go in https://github.com/microsoft/rushstack/blob/main/heft-plugins/heft-typescript-plugin/src/internalTypings/TypeScriptInternals.ts.

File: heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts [hunk 4]
```diff
@@ -1297,12 +1297,16 @@ export class TypeScriptBuilder {
   }
 }
 
+type BuilderProgramWithInternals = TTypescript.BuilderProgram & {
+  state?: { changedFilesSet: Set<string> };
+  getState(): { changedFilesSet: Set<string> };
```
Comment (iclanton) [inline heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts:1302]: Include a doc comment noting that `state` was removed in 5.6 and that `getState` is the replacement.

**Review by iclanton — APPROVED** [review]

File: heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts (hunk 4 above)
Comment (jakebailey) [reply heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts:1302]: (the opposite but yeah)

**Comment by UberMouse** [comment]
Updated

**Review by dmichon-msft — APPROVED** [review]

**Review by D4N14L — APPROVED** [review]
