### ISSUE TITLE
[heft] typescript plugin does not work with Typescript 5.6.2

### ISSUE THREAD

**Issue by UberMouse** [microsoft/rushstack#4921]
## Summary

Just attempted to upgrade to Typescript v5.6.2
Unfortunately something has changed in the typescript internals and now the heft-typescript-plugin crashes when attempting to do a build with the error `builderProgram.getState is not a function` 

## Repro steps

1. Install latest Heft
2. Install latest heft-typescript-plugin
3. Configure a typescript build phase
4. Run `heft build`

  **Expected result:** Program compiles normally

  **Actual result:** Get a crash `builderPrograms.getState is not a function` (not sure how to get heft to give me a stacktrace)

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.66.18 / @rushstack/heft-typescript-plugin 0.5.0 |
| Operating system? | Linux |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | v20.15.1 |

**Comment by iclanton** [comment]
@dmichon-msft - Can you take a look at this?

**Comment by dmichon-msft** [comment]
You can get a stack trace from `heft --debug build`. Likely there have been some breaking changes to internals that we'll have to reconcile.

**Comment by UberMouse** [comment]
It looks like the issue is the changing of `BuilderProgram.getState()` to BuilderProgram.state` in [this](https://github.com/microsoft/TypeScript/commit/b9d96df61f01375da6504f37a31151cfdce0645c) commit. 

I've patched [this](https://github.com/microsoft/rushstack/blob/main/heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts#L1303-L1305) line in the typescript plugin from `builderProgram.getState().changedFIlesSet` to `builderProgram.state.changedFilesSet`and our monorepo built. Watch mode works fine as well.

The patch for reference
```
diff --git a/lib/TypeScriptBuilder.js b/lib/TypeScriptBuilder.js
index 848b58b453095b6807f1d8d9f637cfab4bfe2987..b5668666f7ca4bc40e1379a177ffea7013df2322 100644
--- a/lib/TypeScriptBuilder.js
+++ b/lib/TypeScriptBuilder.js
@@ -782,7 +782,7 @@ class TypeScriptBuilder {
 }
 exports.TypeScriptBuilder = TypeScriptBuilder;
 function getFilesToTranspileFromBuilderProgram(builderProgram) {
-    const changedFilesSet = builderProgram.getState().changedFilesSet;
+    const changedFilesSet = builderProgram.state.changedFilesSet;
     const filesToTranspile = new Map();
     for (const fileName of changedFilesSet) {
         const sourceFile = builderProgram.getSourceFile(fileName);

```
